### ISSUE TITLE
Versão final do site com HTML puro

### ISSUE THREAD

**Issue by MauricioAlmeida** [opensanca/trilha-frontend#1]
Olá Diego, tudo bem?
Hoje recebi uma ligação e tive que sair antes do final da aula.
Acredito que você vai subir tanto o material da aula de hoje (HTML) como também a versão do projeto. Fico no aguardo para poder deixar meu projeto local no mesmo ponto.
Além disso, você tinha comentado que se desse tempo já iria fazer alguma coisa com Bootstrap. Isso rolou?
Eu queria muito assistir isso, mas não teve como não sair mais cedo.
Abraço

**Comment by dkaimoti** [comment]
Opa, td bem e vc?
Acabei de subir os arquivos lá no github do opensanca:
https://github.com/opensanca/trilha-frontend

Quanto ao bootstrap, o que fizemos foi apenas chamar as bibliotecas do Bootstrap, Foundation e Material Design na mesma estrutura HTML que montamos. Deixei esses exemplo na pasta do dia 2.
Dei apenas algumas explicações sobre o sistema de Grids do bootstrap, mas na aula que vem que vou falar do CSS e vamos aplicar no site, abordo novamente isso com mais detalhes e se der tempo até montamos o site só com bootstrap.
Qualquer dúvida, estou à disposição.Abraço! 

```
Em Sábado, 8 de Outubro de 2016 22:38, MauricioAlmeida <notifications@github.com> escreveu:
```

 Olá Diego, tudo bem?
Hoje recebi uma ligação e tive que sair antes do final da aula.
Acredito que você vai subir tanto o material da aula de hoje (HTML) como também a versão do projeto. Fico no aguardo para poder deixar meu projeto local no mesmo ponto.
Além disso, você tinha comentado que se desse tempo já iria fazer alguma coisa com Bootstrap. Isso rolou?
Eu queria muito assistir isso, mas não teve como não sair mais cedo.
Abraço—
