### ISSUE TITLE
Dúvida sobre CSS

### ISSUE THREAD

**Issue by MauricioAlmeida** [opensanca/trilha-frontend#2]
Olá pessoal!

Estou refazendo a formatação do site "do zero" e surgiu uma dúvida que gostaria de uma ajuda para entender direitinho.

No arquivo styles.css, notei que em alguns momentos uma classe "filha" de outra classe é definida no arquivo mencionando a classe "pai" e a "filha", como por exemplo no caso:

```
.instructor .contacts li{
    display: inline-block;
}
```

mas em outros pontos aparece apenas o nome da "filha", como por exemplo em:

```
.title-home {
    font-size: 5.6em;
    color: #fff;
    text-shadow: 0 8px 12px #000;
    text-transform: uppercase;
    padding-top: 15%;
}
```

A dúvida é por que neste último caso não aparece como:

```
.home .title-home {
    font-size: 5.6em;
    color: #fff;
    text-shadow: 0 8px 12px #000;
    text-transform: uppercase;
    padding-top: 15%;
}
```

Se preferir, na próxima aula conversamos sobre o assunto.

Grato

**Comment by dkaimoti** [comment]
Olá Mauricio, td bem?

Nesse caso, deixamos apenas a filha porque essa classe em questão não seria reutilizada em outros lugares, pois as propriedades delas são bem específicas para o título da home, onde não teremos nada igual em outro local do site.

É claro que poderíamos ter deixado ela da mesma forma que as outras com o seletor pai e o filho. Isso deixaria com uma especificidade maior. Mas deixamos assim justamente pelo fato de não reutilizarmos em outros lugar como por exemplo:

```
.home .title{
    font-size: 3em;
    color: #fff;
}

.instructor .title{
    font-size: 2em;
    color: #000;
}
```

Repare que nesse exemplo, usamos a mesma classe, mas aplicamos propriedades diferentes nela. Então, temos um seletor pai diferente pra cada uma.

No caso que você citou, a classe será usada somente em um lugar e com aquelas propriedades, então não houve necessidade de deixar ela com uma especificidade maior.

Qualquer dúvida, é só falar.
Abs!

**Comment by MauricioAlmeida** [comment]
Muito obrigado, Diego.
Ficou bem claro!
